name: CI/CD

on:
  push:
    branches:
      - 'main'

jobs:
  push_docker_images:
    name: 'Build and push docker images'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build notifications-service docker image
        run: |
          cd notifications-service
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/notifications-service:latest

      - name: Build warehouse-service docker image
        run: |
          cd warehouse-service
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/warehouse-service:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push notifications-service to DockerHub
        run: |
          cd notifications-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notifications-service:latest

      - name: Push warehouse-service to DockerHub
        run: |
          cd warehouse-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/warehouse-service:latest
