name: CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  push_docker_images_dockerhub:
    name: "Build and push docker images to Docker Hub"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build notifications-service docker image
        run: |
          cd notifications-service
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/notifications-service:latest

      - name: Build warehouse-service docker image
        run: |
          cd warehouse-service
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/warehouse-service:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push notifications-service
        run: |
          cd notifications-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notifications-service:latest

      - name: Push warehouse-service
        run: |
          cd warehouse-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/warehouse-service:latest

  push_docker_images_yandex_cloud:
    name: "Build and push docker images to YC Registry"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build notifications-service docker image
        run: |
          cd notifications-service
          docker build . -t cr.yandex/${{secrets.YC_REGISTRY_ID }}/${{ secrets.MY_SURNAME }}-notifications-service:latest

      - name: Build warehouse-service docker image
        run: |
          cd warehouse-service
          docker build . -t cr.yandex/${{secrets.YC_REGISTRY_ID }}/${{ secrets.MY_SURNAME }}-warehouse-service:latest

      - name: Login to YC Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}

      - name: Push notifications-service
        run: |
          cd warehouse-service
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/${{ secrets.MY_SURNAME }}-notifications-service:latest

      - name: Push warehouse-service
        run: |
          cd warehouse-service
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/${{ secrets.MY_SURNAME }}-warehouse-service:latest
